// <auto-generated />
using System;
using System.Collections.Generic;
using BookingSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(BookingSystemDbContext))]
    [Migration("20250320065609_UpdateHotel")]
    partial class UpdateHotel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingSystem.Domain.Entities.CurrentRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.PrimitiveCollection<byte[]>("Photos")
                        .IsRequired()
                        .HasColumnType("smallint[]")
                        .HasColumnName("photos");

                    b.Property<int>("number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("roomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id")
                        .HasName("pk_current_room");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("ix_current_room_hotel_id");

                    b.HasIndex("roomId")
                        .HasDatabaseName("ix_current_room_room_id");

                    b.ToTable("current_room", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<float>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f)
                        .HasColumnName("rating");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "BookingSystem.Domain.Entities.Hotel.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Building")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("address_building");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_city");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("address_street");
                        });

                    b.HasKey("Id")
                        .HasName("pk_hotels");

                    b.ToTable("hotels", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("HotelId")
                        .HasColumnType("uuid")
                        .HasColumnName("hotel_id");

                    b.PrimitiveCollection<int[]>("conveniences")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("conveniences");

                    b.Property<int>("roomType")
                        .HasColumnType("integer")
                        .HasColumnName("room_type");

                    b.HasKey("Id")
                        .HasName("pk_room");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("ix_room_hotel_id");

                    b.ToTable("room", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.ComplexProperty<Dictionary<string, object>>("Phone", "BookingSystem.Domain.Entities.User.Phone#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("phoneNumber");
                        });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.CurrentRoom", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Hotel", null)
                        .WithMany("CurrentRooms")
                        .HasForeignKey("HotelId")
                        .HasConstraintName("fk_current_room_hotels_hotel_id");

                    b.HasOne("BookingSystem.Domain.Entities.Room", "room")
                        .WithMany()
                        .HasForeignKey("roomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_current_room_room_room_id");

                    b.Navigation("room");
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Room", b =>
                {
                    b.HasOne("BookingSystem.Domain.Entities.Hotel", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .HasConstraintName("fk_room_hotels_hotel_id");

                    b.OwnsOne("BookingSystem.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("price_currency");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("price_value");

                            b1.HasKey("RoomId");

                            b1.ToTable("room");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("fk_room_room_id");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("BookingSystem.Domain.Entities.Hotel", b =>
                {
                    b.Navigation("CurrentRooms");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
